

export default function hashGoogleSub(googleSub: string): string {

    const pepper = Bun.env.GOOGLE_SUB_PEPPER;

    if (!pepper) {
        throw new Error("Critical Security Error: GOOGLE_SUB_PEPPER environment variable is missing.");
    }

    // TODO: TEST SIMILARITY!
    // hex string generated by Bun's native CryptoHasher("sha256", pepper).digest("hex") 
    // is mathematically identical to C#'s new HMACSHA256(pepper).ComputeHash() hex output

    // NOTE: C# in GoogleUserService.HashGoogleSub
    //  1. Get bytes    byte[] subBytes = Encoding.UTF8.GetBytes(googleSub);
    //  2. Hash it      byte[] hashBytes = hmac.ComputeHash(subBytes);
    //  3. To Hex       Convert.ToHexString(hashBytes);

    // Pass 'sha256' as the algorithm and your pepper as the native hmacKey
    const hasher = new Bun.CryptoHasher("sha256", pepper);

    hasher.update(googleSub);

    // Return as a hex string to save into your database
    return hasher.digest("hex");
}
