// TypeScript may not load Bun's ambient types in editors configured for Node.
// Bun still provides this module at runtime.
// @ts-expect-error Bun's `bun:sqlite` types are supplied by the Bun runtime.
import { Database } from "bun:sqlite";
import { createClient } from "@libsql/client";
import { z } from "zod";
import calculateUserId from './hash'

// Initialize the database file
//const db = new Database("users.sqlite");

const db = createClient({
  url: Bun.env.TURSO_DATABASE_URL!,
  authToken: Bun.env.TURSO_AUTH_TOKEN!,
})




//NOTE: created_at, updated_at are generated by code, not user inputted; no iso8601() or datetime() casts
export const userSchema = z.object({
  id: z.string().min(1, { message: "ID is required" }),
  email: z.email({ message: "Invalid email format" }).max(254, { message: "Email must not exceed 254 characters" }),
  password_hash: z.string().min(1, "Password hash is required"),
  display_name: z.string().nullable(),
  is_moderator: z.number().int().min(0).max(1).default(0),
  created_at: z.string().optional(),
  updated_at: z.string().optional(),
});

// A schema specifically for incoming registration/creation requests 
// (where id, timestamps, and hashes are generated by the server)
export const createUserSchema = z.object({
  email: z.email("Invalid email format").max(254, "Email must not exceed 254 characters"),
  password: z.string().min(8, "Password must be at least 8 characters long").max(128),
  display_name: z.string().nullable().optional(),
});

export type UserInput = z.infer<typeof userSchema>;

// 
export async function createUser(db: any, rawInput: unknown) {


  const validationResult = createUserSchema.safeParse(rawInput);
  
  if (!validationResult.success) {
    //TODO: Test; are 'issues' correct collection?
    throw new Error(`Validation failed: ${validationResult.error.issues.map(issue => issue.message).join(", ")}`);
  }

  const data = validationResult.data;

  // 2. Hash the password using Bun's native utility
  const password_hash = await Bun.password.hash(data.password, {
    algorithm: "argon2id",
    //cost: 4, // default or custom parameters
  });

  const newUser = {
    id: crypto.randomUUID(), // Generate unique string ID
    email: data.email,
    password_hash,
    display_name: data.display_name ?? null,
    is_moderator: 0,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  // 3. Final runtime check against the complete user schema structure
  const validatedUser = userSchema.parse(newUser);

  // 4. Insert into Turso / SQLite
  await db.execute({
    sql: `INSERT INTO user (id, email, password_hash, display_name, is_moderator, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`,
    args: [
      validatedUser.id,
      validatedUser.email,
      validatedUser.password_hash,
      validatedUser.display_name,
      validatedUser.is_moderator,
      validatedUser.created_at,
      validatedUser.updated_at,
    ],
  });

  return validatedUser;
}


/*
db.run(`
  CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    display_name TEXT,
    is_moderator INTEGER DEFAULT 0
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );
`);
*/


// Interface for user objects
export interface User {
  id: string;
  email: string;
  password_hash: string;
  display_name: string | null;
  is_moderator: number ;
  created_at: string;
  updated_at: string;
}

/**
 * Inserts a new user into the database securely.
 * Uses Bun's native password hashing and prepared statements.
 */
export async function createUserOld
  (email: string, passwordPlain: string, displayName: string | null, isModerator: number | null): Promise<void> {
  
  //VALIDATE?
  // SHA-256 hex string is 64 characters long
  const idHash = calculateUserId(email); 
  //new Bun.CryptoHasher("sha256")
  //.update(email.toLowerCase().trim())
  //.digest("hex");
  
  //const id = crypto.randomUUID();
  //const idHash = Bun.hash(email.toLowerCase().trim()).toString(16); 
  const passwordHash = await Bun.password.hash(passwordPlain);

  await db.execute({
    sql: `
      INSERT INTO users (id, email, password_hash, display_name, is_moderator) 
      VALUES ($id, $email, $password_hash, $display_name, $is_moderator)
    `,
    args: {
      id: idHash,
      email: email.toLowerCase().trim(),
      password_hash: passwordHash,
      display_name: displayName,
      is_moderator: isModerator,
    },
  });


}



/**
 * Retrieves a user by their email address.
 * Returns the User object or null if not found.
 */
export async function getUserByEmail(email: string): Promise<User | null> {
  const result = await db.execute({
    sql: "SELECT * FROM user WHERE email = $email",
    args: { email: email.toLowerCase().trim() },
  });
  
  return (result.rows[0] as unknown as User) || null;
}
/*
export function getUserByIdUsingEmail(email: string) {

  const targetId = calculateUserId(email);

  // Uses LIMIT 
  const query = db.query("SELECT * FROM users WHERE id = $id LIMIT 1");
  
  // Execute and return a single object (or null if not found)
  return query.get({ $id: targetId });
}


export function getUserById(id: string): User | null {
  const query = db.query("SELECT * FROM users WHERE id = $id");
  
  return query.get({ $id: id }) as User | null;
}


export function getModeratorUser(id: string): User | null {
  const query = db.query("SELECT * FROM users WHERE id = $id AND is_moderator = 1");

  return query.get({ $id: id }) as User | null;
}



export function updateUserProfile(id: string, displayName: string): void {
  const query = db.query(`
    UPDATE users 
    SET display_name = $display_name, updated_at = CURRENT_TIMESTAMP
    WHERE id = $id
  `);

  query.run({
    $id: id,
    $display_name: displayName,
  });
}


export function getAllUsers(): User[] {
  const query = db.query("SELECT * FROM users ORDER BY created_at DESC");
  
  return query.all() as User[];
}

*/
