const UPLOAD_DIR = "./upload_files";
const THUMB_DIR = "./thumbnails";


/**
 * Calculates perceived luminosity from a hex color string (1 to 100).
 * Supports both 3-digit and 6-digit hex codes (with or without '#').
 * 
 *  --- Example Usage ---
console.log(getLuminosityFromHex('#000000')); // 1 (Black)
console.log(getLuminosityFromHex('#FFFFFF')); // 100 (White)
console.log(getLuminosityFromHex('#FF5733')); // ~49 (Mid lum)
console.log(getLuminosityFromHex('344668'));  // ~19 (test without the '#' symbol)
 */
export default function getLuminosityFromHex(hex: string): number {
	// Remove leading '#' 
	let cleanHex = hex.replace(/^#/, '');

	// "F53" -> "FF5533")
	if (cleanHex.length === 3) {
		cleanHex = cleanHex.split('').map(char => char + char).join('');
	}

	if (cleanHex.length !== 6) {
		throw new Error('Invalid hex color format. Use #RRGGBB or #RGB.');
	}

	// Extract RGB ints
	const r = parseInt(cleanHex.substring(0, 2), 16);
	const g = parseInt(cleanHex.substring(2, 4), 16);
	const b = parseInt(cleanHex.substring(4, 6), 16);

	// Calculate BT.709 luma and scale to 1-100
	const luma = 0.2126 * r + 0.7152 * g + 0.0722 * b;
	const scaled = 1 + (luma / 255) * 99;

	return Math.round(scaled);
}

// extract mask code to segment utility function?
/*
export async function segmentGeminiImage(response : Response, promptText: string, imageFile: Bun.Image): Promise<string> {
    try {
        //const imageBytes =  await imageFile.bytes;

        // Extract the raw image bytes of the generated mask
        const maskBase64 = (response as Response & {
            generatedMasks?: Array<{ mask?: { imageBytes?: string } }>;
        })?.generatedMasks?.[0]?.mask?.imageBytes;

        if (maskBase64) {
            // Save the resulting mask to disk
            const outputBuffer = Buffer.from(maskBase64, 'base64');
            fs.writeFileSync('output_mask.png', outputBuffer);
            console.log('Image segmentation successful! Mask saved to output_mask.png');
        } else {
            console.log('o mask was generated by the model.');
        }

        return "";

    } catch (error) {
        console.error("Error communicating with Gemini:", error);
        return ""; 
    }
}
*/
